from fastapi import FastAPI, Depends, HTTPException, status, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from jose import JWTError, jwt
from passlib.context import CryptContext
from datetime import datetime, timedelta
import pandas as pd
import json
import os
import io
import zipfile
from typing import List, Optional
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
USERS_FILE = os.getenv("USERS_FILE")
origins = [os.getenv("VERCEL_LINK")]

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

class User(BaseModel):
    username: str
    is_admin: bool

class UserCreate(BaseModel):
    username: str
    password: str
    is_admin: bool = False

def load_users():
    if not os.path.exists(USERS_FILE):
        default_user = os.getenv("ADMIN_DEFAULT_USER")
        default_pass = os.getenv("ADMIN_DEFAULT_PASSWORD")
        return {default_user: {"password": pwd_context.hash(default_pass), "is_admin": True}}
    with open(USERS_FILE, 'r') as f:
        return json.load(f)

def save_users(users):
    with open(USERS_FILE, 'w') as f:
        json.dump(users, f, indent=4)

def create_access_token(data: dict):
    to_encode = data.copy()
    expire = datetime.utcnow() + timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    to_encode.update({"exp": expire})
    return jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)

async def get_current_user(token: str = Depends(oauth2_scheme)):
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        username: str = payload.get("sub")
        if username is None:
            raise HTTPException(status_code=401, detail="Invalid credentials")
        users = load_users()
        if username not in users:
            raise HTTPException(status_code=401, detail="User not found")
        return {"username": username, "is_admin": users[username]["is_admin"]}
    except JWTError:
        raise HTTPException(status_code=401, detail="Invalid token")

@app.post("/token")
async def login(form_data: OAuth2PasswordRequestForm = Depends()):
    users = load_users()
    user = users.get(form_data.username)
    if not user or not pwd_context.verify(form_data.password, user["password"]):
        raise HTTPException(status_code=400, detail="Incorrect username or password")
    
    access_token = create_access_token(data={"sub": form_data.username})
    return {"access_token": access_token, "token_type": "bearer", "is_admin": user["is_admin"]}


# --- CORE HELPER FUNCTIONS ---

def read_clean_excel(contents: bytes, filename: str) -> pd.DataFrame:
    """
    Dynamically finds the correct header row and parses the Excel file.
    Supports both .xlsx and .xlsb.
    """
    file_ext = os.path.splitext(filename)[1].lower()
    engine_choice = 'pyxlsb' if file_ext == '.xlsb' else None
    
    # 1. Read first 50 rows without headers to find the table start
    df_temp = pd.read_excel(io.BytesIO(contents), header=None, nrows=50, engine=engine_choice)
    
    # Find the index of the row with the maximum number of non-null values
    header_idx = int(df_temp.notna().sum(axis=1).idxmax())
    
    # 2. Re-read the dataframe using the dynamically discovered header row
    df = pd.read_excel(io.BytesIO(contents), header=header_idx, engine=engine_choice)
    
    # Scrub "Unnamed:" headers generated by Pandas for merged cells
    df.columns = [str(c) if not str(c).startswith("Unnamed:") else "" for c in df.columns]
    
    return df


def create_excel_with_totals(df: pd.DataFrame, output_io: io.BytesIO, with_third_party: bool = False):
    df = df.copy()
    max_col_idx = len(df.columns) - 1
    
    # 1. Define Columns to Keep
    # Base Keep: A(0), C(2), D(3), E(4), H(7), K(10), L(11), M(12), N(13), O(14), P(15), Q(16), R(17)
    # Automatically drops B, F, G, I, J, S, T, U, V, Y, Z+
    base_keep = [0, 2, 3, 4, 7, 10, 11, 12, 13, 14, 15, 16, 17]
    
    if with_third_party:
        # Include W(22) and X(23)
        base_keep.extend([22, 23])
        
    indices_to_keep = [i for i in base_keep if i <= max_col_idx]
    cols_to_keep = [df.columns[i] for i in indices_to_keep]
    
    # 2. Define Columns to Sum
    # Sum P(15) and R(17)
    sum_indices = [15, 17]
    if with_third_party:
        # Sum X(23) as well
        sum_indices.append(23)
        
    valid_sum_indices = [i for i in sum_indices if i <= max_col_idx]
    
    # Force numeric conversion for target sum columns
    for i in valid_sum_indices:
        col_name = df.columns[i]
        df[col_name] = pd.to_numeric(df[col_name], errors='coerce').fillna(0)
        
    df = df.fillna("")
    if 'Combined Name' in df.columns:
        df = df.sort_values(by='Combined Name')
        
    df_out = df[cols_to_keep]
    
    # Map original indices to their new positions in the shrunken dataframe
    original_to_new_loc = {}
    for orig_idx in valid_sum_indices:
        if orig_idx in indices_to_keep:
            original_to_new_loc[orig_idx] = indices_to_keep.index(orig_idx)
    
    # Setup Writer
    writer = pd.ExcelWriter(output_io, engine='xlsxwriter')
    workbook = writer.book
    
    subtotal_fmt = workbook.add_format({'bold': True, 'bg_color': '#E2EFDA'})
    summary_fmt = workbook.add_format({'bold': True, 'bg_color': '#D9E1F2'})
    
    df_out[:0].to_excel(writer, index=False, sheet_name='Summary')
    worksheet = writer.sheets['Summary']
    
    current_row = 1
    
    if 'Combined Name' not in df.columns:
        df['Combined Name'] = "All Data"
    
    # 3. Print Data Chunks and Screen Subtotals
    for screen_name, group in df.groupby('Combined Name', sort=False):
        group_out = group[cols_to_keep]
        group_out.to_excel(writer, index=False, header=False, startrow=current_row, sheet_name='Summary')
        current_row += len(group_out)
        
        screen_val = str(screen_name) if str(screen_name).strip() != "" else "Unknown Screen"
        worksheet.write_string(current_row, 0, f"{screen_val} Subtotal", subtotal_fmt)
        
        # Drop the sums exactly under the correct pruned columns
        for orig_idx in valid_sum_indices:
            if orig_idx in original_to_new_loc:
                new_loc = original_to_new_loc[orig_idx]
                col_name = df.columns[orig_idx]
                val = float(group[col_name].sum())
                worksheet.write_number(current_row, new_loc, val, subtotal_fmt)
                
        current_row += 1 

    # 4. Print Overall Summary at the Bottom
    current_row += 2 
    worksheet.write_string(current_row, 0, "OVERALL SUMMARY", summary_fmt)
    current_row += 1
    
    grand_totals = {orig_idx: 0.0 for orig_idx in valid_sum_indices}
    
    for screen_name, group in df.groupby('Combined Name', sort=False):
        screen_val = str(screen_name) if str(screen_name).strip() != "" else "Unknown Screen"
        worksheet.write_string(current_row, 0, screen_val)
        
        for orig_idx in valid_sum_indices:
            if orig_idx in original_to_new_loc:
                new_loc = original_to_new_loc[orig_idx]
                col_name = df.columns[orig_idx]
                val = float(group[col_name].sum())
                grand_totals[orig_idx] += val
                worksheet.write_number(current_row, new_loc, val)
        current_row += 1
        
    worksheet.write_string(current_row, 0, "Grand Total", summary_fmt)
    for orig_idx in valid_sum_indices:
        if orig_idx in original_to_new_loc:
            new_loc = original_to_new_loc[orig_idx]
            worksheet.write_number(current_row, new_loc, grand_totals[orig_idx], summary_fmt)
            
    writer.close()


# --- API ROUTES ---

@app.post("/extract-theatres")
async def extract_theatres(file: UploadFile = File(...), current_user: dict = Depends(get_current_user)):
    try:
        contents = await file.read()
        df = read_clean_excel(contents, file.filename)
        
        # 1. Get Theatres (Screen Name(D/3) + Screen Code(C/2))
        if len(df.columns) > 3:
            df['Combined Name'] = df.iloc[:, 3].fillna("").astype(str) + " - " + df.iloc[:, 2].fillna("").astype(str)
            theatres = [t for t in df['Combined Name'].unique() if str(t).strip() not in ["-", "nan - nan", ""]]
            theatres.sort()
        else:
            theatres = []
            
        # 2. Get Months from Column A (Index 0)
        months = []
        if len(df.columns) > 0:
            df['Temp Date'] = pd.to_datetime(df.iloc[:, 0], errors='coerce')
            months = df['Temp Date'].dt.strftime('%b-%y').dropna().unique().tolist()
            months.sort(key=lambda date: datetime.strptime(date, "%b-%y"))
            
        return {"theatres": theatres, "months": months}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"File Extraction Error: {str(e)}")


@app.post("/generate-custom-excel")
async def generate_custom_excel(
    file: UploadFile = File(...),
    selected_theatres: str = Form(...),
    with_third_party: str = Form("false"),
    month: str = Form("All"),
    current_user: dict = Depends(get_current_user)
):
    try:
        is_third_party = with_third_party.lower() == "true"
        theatres_list = json.loads(selected_theatres)
        
        contents = await file.read()
        df = read_clean_excel(contents, file.filename)
        
        # Filter by Month in Column A (0)
        if month != "All" and len(df.columns) > 0:
            df['Temp Date'] = pd.to_datetime(df.iloc[:, 0], errors='coerce')
            df = df[df['Temp Date'].dt.strftime('%b-%y') == month]
        
        if len(df.columns) > 3:
            df['Combined Name'] = df.iloc[:, 3].fillna("").astype(str) + " - " + df.iloc[:, 2].fillna("").astype(str)
            filtered_df = df[df['Combined Name'].isin(theatres_list)]
        else:
            filtered_df = df
        
        output = io.BytesIO()
        create_excel_with_totals(filtered_df, output, is_third_party)
        output.seek(0)
        
        return StreamingResponse(
            output, 
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": "attachment; filename=selected_theatres_summary.xlsx"}
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"File Processing Error: {str(e)}")


@app.post("/generate-all-zip")
async def generate_all_zip(
    file: UploadFile = File(...),
    with_third_party: str = Form("false"),
    month: str = Form("All"),
    current_user: dict = Depends(get_current_user)
):
    try:
        is_third_party = with_third_party.lower() == "true"
        contents = await file.read()
        df = read_clean_excel(contents, file.filename)
        
        # Filter by Month in Column A (0)
        if month != "All" and len(df.columns) > 0:
            df['Temp Date'] = pd.to_datetime(df.iloc[:, 0], errors='coerce')
            df = df[df['Temp Date'].dt.strftime('%b-%y') == month]
        
        if len(df.columns) > 3:
            df['Combined Name'] = df.iloc[:, 3].fillna("").astype(str) + " - " + df.iloc[:, 2].fillna("").astype(str)
            unique_theatres = [t for t in df['Combined Name'].unique() if str(t).strip() not in ["-", "nan - nan", ""]]
        else:
            unique_theatres = []
        
        zip_buffer = io.BytesIO()
        
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for theatre_name in unique_theatres:
                theatre_df = df[df['Combined Name'] == theatre_name]
                
                if theatre_df.empty:
                    continue
                    
                output = io.BytesIO()
                create_excel_with_totals(theatre_df, output, is_third_party)
                
                safe_name = str(theatre_name).replace("/", "-").replace("\\", "-")
                zipf.writestr(f"{safe_name}_summary.xlsx", output.getvalue())

        zip_buffer.seek(0)
        return StreamingResponse(
            zip_buffer, 
            media_type="application/x-zip-compressed",
            headers={"Content-Disposition": "attachment; filename=all_theatres_summary.zip"}
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"File Processing Error: {str(e)}")

@app.get("/health")
def health_check():
    return {"status": "healthy"}

@app.get("/ping")
async def ping():
    return {"status": "alive"}

@app.get("/users")
async def get_all_users(current_user: dict = Depends(get_current_user)):
    if not current_user["is_admin"]:
        raise HTTPException(status_code=403, detail="Not authorized")
    users = load_users()
    return [{"username": u, "is_admin": info["is_admin"]} for u, info in users.items()]

@app.post("/users")
async def add_new_user(user: UserCreate, current_user: dict = Depends(get_current_user)):
    if not current_user["is_admin"]:
        raise HTTPException(status_code=403, detail="Not authorized")
    users = load_users()
    if user.username in users:
        raise HTTPException(status_code=400, detail="User already exists")
    users[user.username] = {
        "password": pwd_context.hash(user.password),
        "is_admin": user.is_admin
    }
    save_users(users)
    return {"message": "User created"}

@app.get("/debug")
def debug():
    return {
        "SECRET_KEY": SECRET_KEY,
        "ALGORITHM": ALGORITHM,
        "ACCESS_TOKEN_EXPIRE_MINUTES": ACCESS_TOKEN_EXPIRE_MINUTES,
        "USERS_FILE": USERS_FILE,
        "VERCEL_LINK": os.getenv("VERCEL_LINK"),
        "origins": origins
    }